# AppVeyor (https://ci.appveyor.com/project/dubreuia/intellij-plugin-save-actions)
version: "{branch} {build}"

build:
  verbosity: detailed

# excludes tests (they are using java.nio.Path and are broken on windows)
build_script:
  - gradlew.bat build

# build only main
branches:
  only:
    - main

# build on 64 bit jdk 17
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk17
